#!/usr/bin/env python3
"""Convert a PNG image to an LVGL 8.x C array (LV_IMG_CF_TRUE_COLOR / RGB565).

Usage:
    python3 png_to_lvgl.py <input.png> <output.c> [--height <px>] [--name <symbol>]

Examples:
    python3 scripts/png_to_lvgl.py docs/img/seedsigner_logo.png \
        components/seedsigner/images/seedsigner_logo_img.c \
        --height 80 --name seedsigner_logo_img

The output C file defines:
    const lv_img_dsc_t <name>

with LV_IMG_CF_TRUE_COLOR pixel data (RGB565, 2 bytes per pixel), composited
onto a black background (alpha pre-blended).

Byte-order portability
----------------------
SPI-connected displays (e.g. ESP32 targets) typically require
LV_COLOR_16_SWAP = 1, which changes LVGL's native 16-bit color layout from
little-endian to big-endian byte order.  The generated C file contains BOTH
byte orders behind a compile-time ``#if LV_COLOR_16_SWAP`` guard, so one
generated file works on all targets without runtime overhead.
"""

import argparse
import os
import sys

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required.  Install with: pip install Pillow", file=sys.stderr)
    sys.exit(1)


def convert(src_path: str, dst_path: str, target_height: int, symbol: str) -> None:
    img = Image.open(src_path).convert("RGBA")

    # Resize to target height, maintaining aspect ratio.
    w, h = img.size
    new_h = target_height
    new_w = max(1, round(w * new_h / h))
    img = img.resize((new_w, new_h), Image.LANCZOS)

    raw_rgba = img.tobytes()  # flat RGBA bytes: R G B A R G B A ...
    assert len(raw_rgba) == new_w * new_h * 4

    # Composite onto black background (screensaver BG is always black, so
    # transparency is not needed).  Output LV_IMG_CF_TRUE_COLOR = RGB565,
    # 2 bytes/pixel.  We emit both little-endian (normal) and big-endian
    # (byte-swapped) arrays so the same generated file works on all targets
    # via a compile-time #if LV_COLOR_16_SWAP guard.
    raw_le = bytearray()
    raw_be = bytearray()
    for i in range(0, len(raw_rgba), 4):
        r, g, b, a = raw_rgba[i], raw_rgba[i+1], raw_rgba[i+2], raw_rgba[i+3]
        # Alpha-blend onto black: out = src * alpha / 255
        r = r * a // 255
        g = g * a // 255
        b = b * a // 255
        rgb565 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        raw_le += bytes([rgb565 & 0xFF, (rgb565 >> 8) & 0xFF])  # little-endian
        raw_be += bytes([(rgb565 >> 8) & 0xFF, rgb565 & 0xFF])  # big-endian

    data_size = new_w * new_h * 2  # 2 bytes per pixel (RGB565)
    assert len(raw_le) == data_size
    assert len(raw_be) == data_size

    os.makedirs(os.path.dirname(dst_path) or ".", exist_ok=True)

    with open(dst_path, "w") as f:
        f.write(f"/* Auto-generated by scripts/png_to_lvgl.py — do not edit manually.\n")
        f.write(f" * Source : {os.path.basename(src_path)}\n")
        f.write(f" * Size   : {new_w}x{new_h} px\n")
        f.write(f" * Format : LV_IMG_CF_TRUE_COLOR (2 bytes/pixel: RGB565, composited on black)\n")
        f.write(f" *\n")
        f.write(f" * Contains both LE and BE (byte-swapped) pixel data, selected at compile\n")
        f.write(f" * time via LV_COLOR_16_SWAP.  SPI displays (ESP32) need the swapped\n")
        f.write(f" * variant; parallel/RGB displays and the screenshot generator do not.\n")
        f.write(f" */\n\n")

        # Mirrors the include guard used by lv_font_conv-generated font files:
        # auto-detect whether lvgl.h is directly on the include path.
        f.write(f"#ifdef __has_include\n")
        f.write(f"  #if __has_include(\"lvgl.h\")\n")
        f.write(f"    #ifndef LV_LVGL_H_INCLUDE_SIMPLE\n")
        f.write(f"      #define LV_LVGL_H_INCLUDE_SIMPLE\n")
        f.write(f"    #endif\n")
        f.write(f"  #endif\n")
        f.write(f"#endif\n\n")
        f.write(f"#ifdef LV_LVGL_H_INCLUDE_SIMPLE\n")
        f.write(f"  #include \"lvgl.h\"\n")
        f.write(f"#else\n")
        f.write(f"  #include \"lvgl/lvgl.h\"\n")
        f.write(f"#endif\n\n")

        row_byte_count = new_w * 2

        def write_array(raw: bytearray) -> None:
            for row in range(new_h):
                row_bytes = raw[row * row_byte_count : (row + 1) * row_byte_count]
                hex_vals = ", ".join(f"0x{b:02x}" for b in row_bytes)
                f.write(f"    {hex_vals},\n")

        f.write(f"#if LV_COLOR_16_SWAP\n")
        f.write(f"/* Big-endian (byte-swapped) — for SPI displays */\n")
        f.write(f"static const uint8_t {symbol}_map[{data_size}] = {{\n")
        write_array(raw_be)
        f.write(f"}};\n")
        f.write(f"#else\n")
        f.write(f"/* Little-endian (native) — for parallel/RGB displays and host builds */\n")
        f.write(f"static const uint8_t {symbol}_map[{data_size}] = {{\n")
        write_array(raw_le)
        f.write(f"}};\n")
        f.write(f"#endif\n\n")

        f.write(f"const lv_img_dsc_t {symbol} = {{\n")
        f.write(f"    .header = {{\n")
        f.write(f"        .cf          = LV_IMG_CF_TRUE_COLOR,\n")
        f.write(f"        .always_zero = 0,\n")
        f.write(f"        .reserved    = 0,\n")
        f.write(f"        .w           = {new_w},\n")
        f.write(f"        .h           = {new_h},\n")
        f.write(f"    }},\n")
        f.write(f"    .data_size = {data_size},\n")
        f.write(f"    .data      = {symbol}_map,\n")
        f.write(f"}};\n")

    print(f"Written: {dst_path}  ({new_w}x{new_h}, {data_size} bytes)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert PNG to LVGL C array")
    parser.add_argument("input",  help="Source PNG file")
    parser.add_argument("output", help="Output .c file")
    parser.add_argument("--height", type=int, default=80,
                        help="Target height in pixels (default: 80)")
    parser.add_argument("--name", default="",
                        help="C symbol name (default: output filename stem)")
    args = parser.parse_args()

    symbol = args.name or os.path.splitext(os.path.basename(args.output))[0]
    convert(args.input, args.output, args.height, symbol)


if __name__ == "__main__":
    main()
